
services:
  glassesglam-api:
    container_name: glassesglam-api
    restart: always
    image: node:20.10.0
    ports:
      - 4001:3007
    volumes:
      - ./:/usr/src/glassesGlam
    working_dir: /usr/src/glassesGlam

    networks:
      - monorepo-network

    # FOR PRODUCTION
    command: bash -c "npm install && npm run build && npm run start:prod"


  glassesglam-batch:
    container_name: glassesglam-batch
    restart: unless-stopped
    image: node:20.10.0
    ports:
      - 4002:3008
    volumes:
      - ./:/usr/src/glassesGlam
    working_dir: /usr/src/glassesGlam

    networks:
      - monorepo-network

    # FOR PRODUCTION
    command: bash -c "npm install && npm run build && npm run start:prod:batch"

networks:
  monorepo-network:
    driver: bridge





# glassesglam-next:  localhost:4000 <=> container:3000
# glassesglam-api:   localhost:4001 <=> container:3007
# glassesglam-batch: localhost:4002 <=> container:3008

# docker compose up -d   - yurgizish
# docker compose stop
# docker compose start
# docker compose restart    - yurip turgan holda
# docker compose stop && docker compose rm -f